# Copyright 2020 The 9nFL Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name="link_py")

load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name="pybind11_bazel",
    sha256="6426567481ee345eb48661e7db86adc053881cb4dd39fbf527c8986316b682b9",
    strip_prefix="pybind11_bazel-fc56ce8a8b51e3dd941139d329b63ccfea1d304b",
    urls=[
        "https://github.com/pybind/pybind11_bazel/archive/fc56ce8a8b51e3dd941139d329b63ccfea1d304b.zip",
    ],
)

http_archive(
    name="pybind11",
    build_file="@pybind11_bazel//:pybind11.BUILD",
    urls=["https://github.com/pybind/pybind11/archive/refs/tags/v2.10.4.tar.gz"],
    type="tar.gz",
    sha256="832e2f309c57da9c1e6d4542dedd34b24e4192ecb4d62f6f4866a737454c9970",
    strip_prefix="pybind11-2.10.4",
)

load("@pybind11_bazel//:python_configure.bzl", "python_configure")
python_configure(
    name="local_config_python",
    python_version="3",
)

maybe(
    git_repository,
    name="yacl",
    branch="a1",
    remote="https://github.com/982945902/yacl.git",
)

load("@yacl//bazel:repositories.bzl", "yacl_deps")

yacl_deps()

load(
    "@rules_foreign_cc//foreign_cc:repositories.bzl",
    "rules_foreign_cc_dependencies",
)

rules_foreign_cc_dependencies(
    register_built_tools=False,
    register_default_tools=False,
    register_preinstalled_tools=True,
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

load("@pybind11_bazel//:python_configure.bzl", "python_configure")

python_configure(
    name="local_config_python",
    python_version="3",
)
