# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/contrib/fl/rpc/proto/bridge_agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow/contrib/fl/rpc/proto/bridge_agent.proto',
  package='jdfl',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n2tensorflow/contrib/fl/rpc/proto/bridge_agent.proto\x12\x04jdfl\x1a&tensorflow/core/framework/tensor.proto\"7\n\x0eResponseStatus\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x15\n\rerror_message\x18\x02 \x01(\t\"8\n\x0fPrefetchMessage\x12\x10\n\x08round_id\x18\x01 \x01(\x04\x12\x13\n\x0b\x65xample_ids\x18\x02 \x03(\x04\" \n\x0cStartMessage\x12\x10\n\x08round_id\x18\x01 \x01(\x04\"!\n\rCommitMessage\x12\x10\n\x08round_id\x18\x01 \x01(\x04\"V\n\x0b\x44\x61taMessage\x12\x10\n\x08round_id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\'\n\x06tensor\x18\x03 \x01(\x0b\x32\x17.tensorflow.TensorProto\"\xb7\x01\n\x14TrainerWorkerMessage\x12)\n\x08prefetch\x18\x01 \x01(\x0b\x32\x15.jdfl.PrefetchMessageH\x00\x12#\n\x05start\x18\x02 \x01(\x0b\x32\x12.jdfl.StartMessageH\x00\x12%\n\x06\x63ommit\x18\x03 \x01(\x0b\x32\x13.jdfl.CommitMessageH\x00\x12!\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x11.jdfl.DataMessageH\x00\x42\x05\n\x03msg\"7\n\x14LoadDataBlockRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x04\x12\x10\n\x08\x62lock_id\x18\x02 \x01(\t\"=\n\x0e\x43onnectRequest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x13\n\x0bworker_rank\x18\x02 \x01(\r\">\n\x0f\x43onnectResponse\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x13\n\x0bworker_rank\x18\x02 \x01(\r\"\x12\n\x10HeartbeatRequest\"Z\n\x11HeartbeatResponse\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x13\n\x0bworker_rank\x18\x02 \x01(\r\x12\x18\n\x10\x63urrent_round_id\x18\x03 \x01(\x04\x62\x06proto3')
  ,
  dependencies=[tensorflow_dot_core_dot_framework_dot_tensor__pb2.DESCRIPTOR,])




_RESPONSESTATUS = _descriptor.Descriptor(
  name='ResponseStatus',
  full_name='jdfl.ResponseStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='jdfl.ResponseStatus.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='jdfl.ResponseStatus.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=155,
)


_PREFETCHMESSAGE = _descriptor.Descriptor(
  name='PrefetchMessage',
  full_name='jdfl.PrefetchMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='round_id', full_name='jdfl.PrefetchMessage.round_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='example_ids', full_name='jdfl.PrefetchMessage.example_ids', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=213,
)


_STARTMESSAGE = _descriptor.Descriptor(
  name='StartMessage',
  full_name='jdfl.StartMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='round_id', full_name='jdfl.StartMessage.round_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=247,
)


_COMMITMESSAGE = _descriptor.Descriptor(
  name='CommitMessage',
  full_name='jdfl.CommitMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='round_id', full_name='jdfl.CommitMessage.round_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=282,
)


_DATAMESSAGE = _descriptor.Descriptor(
  name='DataMessage',
  full_name='jdfl.DataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='round_id', full_name='jdfl.DataMessage.round_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='jdfl.DataMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tensor', full_name='jdfl.DataMessage.tensor', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=370,
)


_TRAINERWORKERMESSAGE = _descriptor.Descriptor(
  name='TrainerWorkerMessage',
  full_name='jdfl.TrainerWorkerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefetch', full_name='jdfl.TrainerWorkerMessage.prefetch', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='jdfl.TrainerWorkerMessage.start', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commit', full_name='jdfl.TrainerWorkerMessage.commit', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='jdfl.TrainerWorkerMessage.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='jdfl.TrainerWorkerMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=373,
  serialized_end=556,
)


_LOADDATABLOCKREQUEST = _descriptor.Descriptor(
  name='LoadDataBlockRequest',
  full_name='jdfl.LoadDataBlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='jdfl.LoadDataBlockRequest.count', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_id', full_name='jdfl.LoadDataBlockRequest.block_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=613,
)


_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='jdfl.ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='application_id', full_name='jdfl.ConnectRequest.application_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_rank', full_name='jdfl.ConnectRequest.worker_rank', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=676,
)


_CONNECTRESPONSE = _descriptor.Descriptor(
  name='ConnectResponse',
  full_name='jdfl.ConnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='application_id', full_name='jdfl.ConnectResponse.application_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_rank', full_name='jdfl.ConnectResponse.worker_rank', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=678,
  serialized_end=740,
)


_HEARTBEATREQUEST = _descriptor.Descriptor(
  name='HeartbeatRequest',
  full_name='jdfl.HeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=742,
  serialized_end=760,
)


_HEARTBEATRESPONSE = _descriptor.Descriptor(
  name='HeartbeatResponse',
  full_name='jdfl.HeartbeatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='application_id', full_name='jdfl.HeartbeatResponse.application_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_rank', full_name='jdfl.HeartbeatResponse.worker_rank', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_round_id', full_name='jdfl.HeartbeatResponse.current_round_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=762,
  serialized_end=852,
)

_DATAMESSAGE.fields_by_name['tensor'].message_type = tensorflow_dot_core_dot_framework_dot_tensor__pb2._TENSORPROTO
_TRAINERWORKERMESSAGE.fields_by_name['prefetch'].message_type = _PREFETCHMESSAGE
_TRAINERWORKERMESSAGE.fields_by_name['start'].message_type = _STARTMESSAGE
_TRAINERWORKERMESSAGE.fields_by_name['commit'].message_type = _COMMITMESSAGE
_TRAINERWORKERMESSAGE.fields_by_name['data'].message_type = _DATAMESSAGE
_TRAINERWORKERMESSAGE.oneofs_by_name['msg'].fields.append(
  _TRAINERWORKERMESSAGE.fields_by_name['prefetch'])
_TRAINERWORKERMESSAGE.fields_by_name['prefetch'].containing_oneof = _TRAINERWORKERMESSAGE.oneofs_by_name['msg']
_TRAINERWORKERMESSAGE.oneofs_by_name['msg'].fields.append(
  _TRAINERWORKERMESSAGE.fields_by_name['start'])
_TRAINERWORKERMESSAGE.fields_by_name['start'].containing_oneof = _TRAINERWORKERMESSAGE.oneofs_by_name['msg']
_TRAINERWORKERMESSAGE.oneofs_by_name['msg'].fields.append(
  _TRAINERWORKERMESSAGE.fields_by_name['commit'])
_TRAINERWORKERMESSAGE.fields_by_name['commit'].containing_oneof = _TRAINERWORKERMESSAGE.oneofs_by_name['msg']
_TRAINERWORKERMESSAGE.oneofs_by_name['msg'].fields.append(
  _TRAINERWORKERMESSAGE.fields_by_name['data'])
_TRAINERWORKERMESSAGE.fields_by_name['data'].containing_oneof = _TRAINERWORKERMESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['ResponseStatus'] = _RESPONSESTATUS
DESCRIPTOR.message_types_by_name['PrefetchMessage'] = _PREFETCHMESSAGE
DESCRIPTOR.message_types_by_name['StartMessage'] = _STARTMESSAGE
DESCRIPTOR.message_types_by_name['CommitMessage'] = _COMMITMESSAGE
DESCRIPTOR.message_types_by_name['DataMessage'] = _DATAMESSAGE
DESCRIPTOR.message_types_by_name['TrainerWorkerMessage'] = _TRAINERWORKERMESSAGE
DESCRIPTOR.message_types_by_name['LoadDataBlockRequest'] = _LOADDATABLOCKREQUEST
DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectResponse'] = _CONNECTRESPONSE
DESCRIPTOR.message_types_by_name['HeartbeatRequest'] = _HEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['HeartbeatResponse'] = _HEARTBEATRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseStatus = _reflection.GeneratedProtocolMessageType('ResponseStatus', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESTATUS,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.ResponseStatus)
  })
_sym_db.RegisterMessage(ResponseStatus)

PrefetchMessage = _reflection.GeneratedProtocolMessageType('PrefetchMessage', (_message.Message,), {
  'DESCRIPTOR' : _PREFETCHMESSAGE,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.PrefetchMessage)
  })
_sym_db.RegisterMessage(PrefetchMessage)

StartMessage = _reflection.GeneratedProtocolMessageType('StartMessage', (_message.Message,), {
  'DESCRIPTOR' : _STARTMESSAGE,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.StartMessage)
  })
_sym_db.RegisterMessage(StartMessage)

CommitMessage = _reflection.GeneratedProtocolMessageType('CommitMessage', (_message.Message,), {
  'DESCRIPTOR' : _COMMITMESSAGE,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.CommitMessage)
  })
_sym_db.RegisterMessage(CommitMessage)

DataMessage = _reflection.GeneratedProtocolMessageType('DataMessage', (_message.Message,), {
  'DESCRIPTOR' : _DATAMESSAGE,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.DataMessage)
  })
_sym_db.RegisterMessage(DataMessage)

TrainerWorkerMessage = _reflection.GeneratedProtocolMessageType('TrainerWorkerMessage', (_message.Message,), {
  'DESCRIPTOR' : _TRAINERWORKERMESSAGE,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.TrainerWorkerMessage)
  })
_sym_db.RegisterMessage(TrainerWorkerMessage)

LoadDataBlockRequest = _reflection.GeneratedProtocolMessageType('LoadDataBlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOADDATABLOCKREQUEST,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.LoadDataBlockRequest)
  })
_sym_db.RegisterMessage(LoadDataBlockRequest)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

ConnectResponse = _reflection.GeneratedProtocolMessageType('ConnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTRESPONSE,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.ConnectResponse)
  })
_sym_db.RegisterMessage(ConnectResponse)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.HeartbeatRequest)
  })
_sym_db.RegisterMessage(HeartbeatRequest)

HeartbeatResponse = _reflection.GeneratedProtocolMessageType('HeartbeatResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATRESPONSE,
  '__module__' : 'tensorflow.contrib.fl.rpc.proto.bridge_agent_pb2'
  # @@protoc_insertion_point(class_scope:jdfl.HeartbeatResponse)
  })
_sym_db.RegisterMessage(HeartbeatResponse)


# @@protoc_insertion_point(module_scope)
