# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from fl_comm_libs.proto import dc_agent_pb2 as fl__comm__libs_dot_proto_dot_dc__agent__pb2


class DataBlockQueryServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.QueryDataBlock = channel.unary_unary(
        '/jdfl.DataBlockQueryService/QueryDataBlock',
        request_serializer=fl__comm__libs_dot_proto_dot_dc__agent__pb2.FetchDataBlockRequest.SerializeToString,
        response_deserializer=fl__comm__libs_dot_proto_dot_dc__agent__pb2.FetchDataBlockResponse.FromString,
        )


class DataBlockQueryServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def QueryDataBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataBlockQueryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'QueryDataBlock': grpc.unary_unary_rpc_method_handler(
          servicer.QueryDataBlock,
          request_deserializer=fl__comm__libs_dot_proto_dot_dc__agent__pb2.FetchDataBlockRequest.FromString,
          response_serializer=fl__comm__libs_dot_proto_dot_dc__agent__pb2.FetchDataBlockResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'jdfl.DataBlockQueryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
