# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interconnection_psi/interconnection/runtime/ecdh_psi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:interconnection_psi/interconnection/runtime/ecdh_psi.proto\x12\x1eorg.interconnection.v2.runtime\"q\n\x12\x45\x63\x64hPsiCipherBatch\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x13\n\x0b\x62\x61tch_index\x18\x03 \x01(\x05\x12\x15\n\ris_last_batch\x18\x04 \x01(\x08\x12\r\n\x05\x63ount\x18\x06 \x01(\x05\x12\x12\n\nciphertext\x18\x07 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interconnection_psi.interconnection.runtime.ecdh_psi_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ECDHPSICIPHERBATCH']._serialized_start=94
  _globals['_ECDHPSICIPHERBATCH']._serialized_end=207
# @@protoc_insertion_point(module_scope)
