# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\x1a\x19google/protobuf/any.proto\"\x9e\x01\n\rRequestHeader\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x32\n\x08metadata\x18\x02 \x03(\x0b\x32 .api.RequestHeader.MetadataEntry\x1a\x45\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\"\xb7\x01\n\x0cResultHeader\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x31\n\x08metadata\x18\x02 \x03(\x0b\x32\x1f.api.ResultHeader.MetadataEntry\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x12\x0b\n\x03msg\x18\x04 \x01(\t\x1a\x45\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\"E\n\x11PsiExecuteRequest\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.api.RequestHeader\x12\x0c\n\x04keys\x18\t \x03(\x0c\"C\n\x10PsiExecuteResult\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.api.ResultHeader\x12\x0c\n\x04keys\x18\t \x03(\x0c\x32\x98\x01\n\x0e\x45xecuteService\x12=\n\nPsiExecute\x12\x16.api.PsiExecuteRequest\x1a\x15.api.PsiExecuteResult\"\x00\x12G\n\x10PsiStreamExecute\x12\x16.api.PsiExecuteRequest\x1a\x15.api.PsiExecuteResult\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTHEADER_METADATAENTRY']._options = None
  _globals['_REQUESTHEADER_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RESULTHEADER_METADATAENTRY']._options = None
  _globals['_RESULTHEADER_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_REQUESTHEADER']._serialized_start=46
  _globals['_REQUESTHEADER']._serialized_end=204
  _globals['_REQUESTHEADER_METADATAENTRY']._serialized_start=135
  _globals['_REQUESTHEADER_METADATAENTRY']._serialized_end=204
  _globals['_RESULTHEADER']._serialized_start=207
  _globals['_RESULTHEADER']._serialized_end=390
  _globals['_RESULTHEADER_METADATAENTRY']._serialized_start=135
  _globals['_RESULTHEADER_METADATAENTRY']._serialized_end=204
  _globals['_PSIEXECUTEREQUEST']._serialized_start=392
  _globals['_PSIEXECUTEREQUEST']._serialized_end=461
  _globals['_PSIEXECUTERESULT']._serialized_start=463
  _globals['_PSIEXECUTERESULT']._serialized_end=530
  _globals['_EXECUTESERVICE']._serialized_start=533
  _globals['_EXECUTESERVICE']._serialized_end=685
# @@protoc_insertion_point(module_scope)
