# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interconnection_psi/interconnection/handshake/algos/psi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=interconnection_psi/interconnection/handshake/algos/psi.proto\x12\x1corg.interconnection.v2.algos\"[\n\x13PsiDataInfoProposal\x12\x1a\n\x12supported_versions\x18\x01 \x03(\x05\x12\x10\n\x08item_num\x18\x02 \x01(\x03\x12\x16\n\x0eresult_to_rank\x18\x03 \x01(\x05\"<\n\x11PsiDataInfoResult\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x16\n\x0eresult_to_rank\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interconnection_psi.interconnection.handshake.algos.psi_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PSIDATAINFOPROPOSAL']._serialized_start=95
  _globals['_PSIDATAINFOPROPOSAL']._serialized_end=186
  _globals['_PSIDATAINFORESULT']._serialized_start=188
  _globals['_PSIDATAINFORESULT']._serialized_end=248
# @@protoc_insertion_point(module_scope)
