# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataJoin/common/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DataJoin/common/common.proto',
  package='DataJoin.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1c\x44\x61taJoin/common/common.proto\x12\x0f\x44\x61taJoin.common\"J\n\x06Status\x12)\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1b.DataJoin.common.StatusCode\x12\x15\n\rerror_message\x18\x02 \x01(\t\"{\n\x0e\x44\x61taSourceMeta\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rpartition_num\x18\x02 \x01(\r\x12\x12\n\nstart_time\x18\x03 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x03\x12\x1e\n\x16negative_sampling_rate\x18\x05 \x01(\x02\"\xd0\x01\n\nDataSource\x12\x18\n\x10\x64\x61ta_source_name\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x61ta_block_dir\x18\x02 \x01(\t\x12\x14\n\x0craw_data_dir\x18\x03 \x01(\t\x12\x14\n\x0cpartition_id\x18\x04 \x01(\r\x12\x0c\n\x04mode\x18\x05 \x01(\t\x12%\n\x04role\x18\x06 \x01(\x0e\x32\x17.DataJoin.common.FLRole\x12/\n\x05state\x18\x07 \x01(\x0e\x32 .DataJoin.common.DataSourceState*o\n\nStatusCode\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12\x18\n\x14STATUS_UNKNOWN_ERROR\x10\x01\x12\x1a\n\x16STATUS_INVALID_REQUEST\x10\x02\x12\x17\n\x13STATUS_NO_MORE_DATA\x10\x03*\"\n\x06\x46LRole\x12\n\n\x06Leader\x10\x00\x12\x0c\n\x08\x46ollower\x10\x01*]\n\x0f\x44\x61taSourceState\x12\x0b\n\x07UnKnown\x10\x00\x12\x08\n\x04Init\x10\x01\x12\x0e\n\nProcessing\x10\x02\x12\t\n\x05Ready\x10\x03\x12\x0c\n\x08\x46inished\x10\x04\x12\n\n\x06\x46\x61iled\x10\x05\x62\x06proto3')
)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='DataJoin.common.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNKNOWN_ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_INVALID_REQUEST', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_NO_MORE_DATA', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=461,
  serialized_end=572,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
_FLROLE = _descriptor.EnumDescriptor(
  name='FLRole',
  full_name='DataJoin.common.FLRole',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Leader', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Follower', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=574,
  serialized_end=608,
)
_sym_db.RegisterEnumDescriptor(_FLROLE)

FLRole = enum_type_wrapper.EnumTypeWrapper(_FLROLE)
_DATASOURCESTATE = _descriptor.EnumDescriptor(
  name='DataSourceState',
  full_name='DataJoin.common.DataSourceState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnKnown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Init', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Processing', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Ready', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Finished', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=610,
  serialized_end=703,
)
_sym_db.RegisterEnumDescriptor(_DATASOURCESTATE)

DataSourceState = enum_type_wrapper.EnumTypeWrapper(_DATASOURCESTATE)
STATUS_SUCCESS = 0
STATUS_UNKNOWN_ERROR = 1
STATUS_INVALID_REQUEST = 2
STATUS_NO_MORE_DATA = 3
Leader = 0
Follower = 1
UnKnown = 0
Init = 1
Processing = 2
Ready = 3
Finished = 4
Failed = 5



_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='DataJoin.common.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='DataJoin.common.Status.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='DataJoin.common.Status.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=123,
)


_DATASOURCEMETA = _descriptor.Descriptor(
  name='DataSourceMeta',
  full_name='DataJoin.common.DataSourceMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DataJoin.common.DataSourceMeta.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partition_num', full_name='DataJoin.common.DataSourceMeta.partition_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='DataJoin.common.DataSourceMeta.start_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='DataJoin.common.DataSourceMeta.end_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='negative_sampling_rate', full_name='DataJoin.common.DataSourceMeta.negative_sampling_rate', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=248,
)


_DATASOURCE = _descriptor.Descriptor(
  name='DataSource',
  full_name='DataJoin.common.DataSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_source_name', full_name='DataJoin.common.DataSource.data_source_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_block_dir', full_name='DataJoin.common.DataSource.data_block_dir', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_data_dir', full_name='DataJoin.common.DataSource.raw_data_dir', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partition_id', full_name='DataJoin.common.DataSource.partition_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='DataJoin.common.DataSource.mode', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='DataJoin.common.DataSource.role', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='DataJoin.common.DataSource.state', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=459,
)

_STATUS.fields_by_name['code'].enum_type = _STATUSCODE
_DATASOURCE.fields_by_name['role'].enum_type = _FLROLE
_DATASOURCE.fields_by_name['state'].enum_type = _DATASOURCESTATE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['DataSourceMeta'] = _DATASOURCEMETA
DESCRIPTOR.message_types_by_name['DataSource'] = _DATASOURCE
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
DESCRIPTOR.enum_types_by_name['FLRole'] = _FLROLE
DESCRIPTOR.enum_types_by_name['DataSourceState'] = _DATASOURCESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'DataJoin.common.common_pb2'
  # @@protoc_insertion_point(class_scope:DataJoin.common.Status)
  })
_sym_db.RegisterMessage(Status)

DataSourceMeta = _reflection.GeneratedProtocolMessageType('DataSourceMeta', (_message.Message,), {
  'DESCRIPTOR' : _DATASOURCEMETA,
  '__module__' : 'DataJoin.common.common_pb2'
  # @@protoc_insertion_point(class_scope:DataJoin.common.DataSourceMeta)
  })
_sym_db.RegisterMessage(DataSourceMeta)

DataSource = _reflection.GeneratedProtocolMessageType('DataSource', (_message.Message,), {
  'DESCRIPTOR' : _DATASOURCE,
  '__module__' : 'DataJoin.common.common_pb2'
  # @@protoc_insertion_point(class_scope:DataJoin.common.DataSource)
  })
_sym_db.RegisterMessage(DataSource)


# @@protoc_insertion_point(module_scope)
